- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
  - name: Upgrade all packages
    become: true
    dnf:
      name: "*"
      state: latest
  tasks:
  - import_tasks: tasks/zsh.yml
  - import_tasks: tasks/neovim.yml
  - import_tasks: tasks/ssh.yml
  - import_tasks: tasks/git_setup.yml
  - import_tasks: tasks/dotfiles.yml
  - import_tasks: tasks/go.yml
  - import_tasks: tasks/productivity.yml
