- name: Install build requirements
  become: true
  dnf:
    name: [ "ninja-build", "libtool", "autoconf", "automake", "cmake", "gcc", "gcc-c++", "make", "pkgconfig"]
  tags:
    - neovim
    - install
    - core
- name: Install System Packages 2
  become: true
  dnf:
    name: [ "unzip", "patch", "gettext", "curl" ]
  tags:
    - neovim
    - install
    - core
- name: Install System Packages 3
  become: true
  dnf:
    name: [ "libtool", "libstdc++-static", "clang" ]
  tags:
    - install
    - core
