- name: Installing stow
  dnf: name=stow
  tags:
    - dotfiles
- name: Clone .dotfiles
  git:
    repo: 'git@github.com:patnick/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    accept_hostkey: yes
    version: main
  tags:
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./fedora.sh
  tags:
    - dotfiles
