- name: Installing stow
  become: true
  dnf: name=stow
  tags:
    - dotfiles
- name: Prep dotfiles
  file:
    owner: pat
    group: pat
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
  file:
    owner: pat
    group: pat
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory
  tags:
    - dotfiles
- name: Clone .dotfiles
  git:
    repo: 'git@github.com:patnick/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    accept_hostkey: yes
    version: main
  tags:
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./fedora.sh
  tags:
    - dotfiles
