- name: Remove go
  become: true
  file:
    path: "/usr/local/go"
    state: absent
  tags:
    - go
- name: Download and install Go
  become: true
  ansible.builtin.unarchive:
    src: https://go.dev/dl/go1.22.0.linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: yes
  tags:
    - go
- name: Install delve
  shell: /usr/local/go/bin/go install github.com/go-delve/delve/cmd/dlv@latest
  tags:
  - go
- name: Install gopls
  shell: /usr/local/go/bin/go install golang.org/x/tools/gopls@latest
  tags:
  - go
