- name: Remove go
  become: true
  file:
    path: "/usr/local/go"
    state: absent
  tags:
    - go
- name: Unarchive a file that needs to be downloaded
  become: true
  ansible.builtin.unarchive:
    src: https://go.dev/dl/go1.20.1.linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: yes
  tags:
    - go
- name: Install delve
  shell: /usr/local/go/bin/go install github.com/go-delve/delve/cmd/dlv@latest
  tags:
  - go
