- name: Install lua
  become: true
  dnf:
    name: ["lua", "lua-devel"]
  tags:
    - lua
- name: Setup sumneko lua lsp
  git:
    repo: "git@github.com:sumneko/lua-language-server.git"
    dest: "{{ lookup('env', 'HOME') }}/sumneko"
    recursive: yes
    accept_hostkey: yes
  tags:
    - lua_lsp
- name: Build Sumneko
  shell:
    cmd: ./compile/install.sh
    chdir: "{{ lookup('env', 'HOME') }}/sumneko/3rd/luamake"
  tags:
    - lua_lsp
- name: Finish Build Sumneko
  shell:
    cmd: ./3rd/luamake/luamake rebuild
    chdir: "{{ lookup('env', 'HOME') }}/sumneko/"
  tags:
    - lua_lsp
- name: Neovim Plugin Development 1
  become: true
  dnf:
    name: "luarocks"
  tags:
    - lua_lsp
