- name: Remove neovim
  file:
    path: "{{ lookup('env', 'HOME') }}/neovim"
    state: absent
  tags:
    - neovim
- name: Clone neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - neovim
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=Release"
  tags:
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - neovim
- name: Prep for Packer
  shell: mkdir -p ~/.local/share
  tags:
    - neovim
- name: Install Packer
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    depth: 1
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
  - neovim
