- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - neovim
- name: Clone neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
    single_branch: yes
    version: release-0.7
  tags:
    - neovim
- name: Install build requirements
  dnf:
    name: [ "ninja-build","libtool","autoconf","automake","cmake","gcc","gcc-c++","make","pkgconfig","unzip","patch","gettext","curl" ]
  tags:
    - neovim
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=Release -j 8"
  tags:
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - neovim
- name: Install Vim-Plug
  shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags:
    - neovim
    - dotfiles
