- name: Install zsh
  become: true
  dnf: name=zsh
  tags:
  - zsh
- name: Change shell
  become: true
  shell: chsh -s `which zsh` pat
  tags:
  - zsh
- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  tags:
  - zsh
- name: Install zsh plugin autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
  - zsh
- name: Install zsh plugin syntax highlighting
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags:
  - zsh
- name: Remove default zshrc so I can Stow mine
  shell: rm -f ~/.zshrc
  tags:
  - zsh
